name: Generate Changelog with Lerna

on:
  push:
    branches:
      # - master

jobs:
  update-changelog:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    # 1. Checkout репозитория
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Configure Git author
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"

    # 2. Установка Node.js
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    # 3. Установка зависимостей
    - name: Install dependencies
      run: |
        npm install
        npm install -g lerna

    # 4. Генерация CHANGELOG для каждого пакета с помощью Lerna
    - name: Generate Changelogs
      uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          // Получить сообщение последнего коммита
          COMMIT_MESSAGE=$(git log -1 --format=%B)

          // Разбить сообщение на строки
          while IFS= read -r line; do
            // Извлечь название пакета из строки
            PACKAGE=$(echo "$line" | grep -oP '\(\K[^)]+')
            
            if [ -n "$PACKAGE" ]; then
              case $PACKAGE in
                front-end)
                  npm run changelog:front-end
                  ;;
                plugin-component)
                  npm run changelog:plugin-component
                  ;;
                root)
                  npm run changelog:root
                  ;;
              esac
            fi
          done <<< "$COMMIT_MESSAGE"
      # run: |
      #   # npx lerna version --conventional-commits --yes --no-push
      #   # npm run changelog:all
      #   git add . 
    - name: Add changelog details
      run: |
        npx lerna version --conventional-commits --yes --no-push
       
        git add . 

    - name: Set up GitHub authentication
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo "//registry.npmjs.org/:_authToken=${GITHUB_TOKEN}" > .npmrc

    # 6. Коммит и пуш изменений
    - name: Commit and Push Changelog Updates
      run: |
        if git diff --cached --quiet; then
          echo "No changes detected, skipping commit."
        else
          git commit -m "chore: update CHANGELOGs [skip ci]"
          git push
        fi
