name: Generate Changelog and Release

on:
  workflow_dispatch:
    inputs:
      node_version:
      publish_front:
        required: true
        default: 'false'
        type: boolean
        description: 'Release front-end'
      publish_plugin:
        required: true
        default: 'false'
        type: boolean
        description: 'Release plugin-1'
      publish_root:
        required: true
        default: 'false'
        type: boolean
        description: 'Release root'

jobs:
  generate-and-release-front-end:
   runs-on: ubuntu-latest
   permissions:
      contents: 'write'
      packages: 'write'
  
   if: ${{ inputs.publish_front == true }}
   steps:
      # 1.1 Checkout репозиторий
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Убедитесь, что весь репозиторий загружен, включая историю коммитов

      # 2.1 Установить зависимости
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

       # 3.1 Установить зависимости для работы с git
      - name: Install dependencies
        run: |
          npm install -g conventional-changelog-cli

       # 4.1 Проверить изменения в front-end
      - name: Check changes in front-end
        id: changes-front-end
        run: |
          # Обновляем локальные данные о ветке master
          git fetch origin master

          # Проверяем, существует ли ветка master на удалённом репозитории
          BASE_BRANCH="origin/master"
          if git rev-parse --verify $BASE_BRANCH >/dev/null 2>&1; then
            # Находим общий предок между текущей веткой и master
            BASE_COMMIT=$(git merge-base HEAD $BASE_BRANCH)
          else
            echo "No common ancestor found. Using initial commit as base."
            BASE_COMMIT=$(git rev-list --max-parents=0 HEAD)
          fi

          # Сравниваем изменения в front-end относительно базового коммита
          git diff --quiet $BASE_COMMIT HEAD -- packages/front-end || echo "Changes detected" >> $GITHUB_ENV

          # Если изменения есть, сохраняем флаг
          if [ $? -eq 0 ]; then
            echo "changes=true" >> $GITHUB_ENV
          else
            echo "changes=false" >> $GITHUB_ENV
          fi

       # 5.1 Сбор данных коммитов
      
      - name: Generate changelog for front-end
        # if: ${{ steps.setup.outputs.pr-running != 'true' && inputs.publish_components != true && inputs.publish_editor != true }}
        if: env.changes == 'true'
        run: |
          # Генерация CHANGELOG.md для front-end
          npm run changelog:front-end

      # 6. Закоммитить изменения в changelog
      - name: Commit changelog updates
        if: env.changes == 'true'
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add packages/front-end/CHANGELOG.md
          git commit -m "chore(front-end): update changelog [skip ci]" || echo "No changes to commit"
      
      # 7. Запушить изменения
      - name: Push changelog to repository
        if: env.changes == 'true'
        run: |
          git push origin HEAD

      # 6.1 Создать релиз для front-end, если есть изменения
      - name: Create GitHub Release for front-end
        if: env.changes == 'true'
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: front-end-v${{ github.run_id }}
          release_name: front-end Release v${{ github.run_id }}
          draft: false
          prerelease: false
          body: |
            See the latest changes for front-end in [CHANGELOG.md](packages/front-end/CHANGELOG.md).

      - name: Save Release ID
        run: |
          echo "RELEASE_ID=${{ steps.create_release.outputs.id }}" >> $GITHUB_ENV
          echo "Release URL: https://github.com/${{ github.repository }}/releases/tag/${{ steps.create_release.outputs.tag_name }}"

  generate-and-release-plugin-1:
    runs-on: ubuntu-latest
    permissions:
      contents: 'write'
      packages: 'write'

    if: ${{ inputs.publish_plugin == true }}
    steps:
      # 1.2 Checkout репозиторий
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Убедитесь, что весь репозиторий загружен, включая историю коммитов

      # 2.2 Установить зависимости
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # 3.2 Установить зависимости для работы с git
      - name: Install dependencies
        run: |
          npm install -g conventional-changelog-cli

      # 4.2 Проверить изменения в plugin-1
      - name: Check changes in plugin-1
        id: changes-plugin-1
        run: |
          # Обновляем локальные данные о ветке master
          git fetch origin master

          # Проверяем, существует ли ветка master на удалённом репозитории
          BASE_BRANCH="origin/master"
          if git rev-parse --verify $BASE_BRANCH >/dev/null 2>&1; then
            # Находим общий предок между текущей веткой и master
            BASE_COMMIT=$(git merge-base HEAD $BASE_BRANCH)
          else
            echo "No common ancestor found. Using initial commit as base."
            BASE_COMMIT=$(git rev-list --max-parents=0 HEAD)
          fi

          # Сравниваем изменения в plugin-1 относительно базового коммита
          git diff $BASE_COMMIT HEAD -- packages/plugin-1/ > changes.diff

          # Если изменения есть в plugin-1, сохраняем флаг
          if [ -s changes.diff ]; then
            echo "changes=true" >> $GITHUB_ENV
          else
            echo "changes=false" >> $GITHUB_ENV
          fi
          
      # 5.2 Сбор данных коммитов
      - name: Generate changelog for plugin-1
        if: env.changes == 'true'
        run: |
          # Генерация CHANGELOG.md для plugin-1
          npm run changelog:plugin-1

      # 6. Закоммитить изменения в changelog
      - name: Commit changelog updates
        if: env.changes == 'true'
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add packages/plugin-1/CHANGELOG.md
          git commit -m "chore(plugin-1): update changelog [skip ci]" || echo "No changes to commit"
      
      # 7. Запушить изменения
      - name: Push changelog to repository
        if: env.changes == 'true'
        run: |
          git push origin HEAD

      # 6.2 Создать релиз для plugin-1, если есть изменения
      - name: Create GitHub Release for plugin-1
        id: create_release
        if: env.changes == 'true'
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: plugin-1-v${{ github.run_id }}
          release_name: plugin-1 Release v${{ github.run_id }}
          draft: false
          prerelease: false
          body: |
            See the latest changes for plugin-1 in [CHANGELOG.md](packages/plugin-1/CHANGELOG.md).
      
      # - name: Save Release ID
      #   run: |
      #     echo "RELEASE_ID=${{ steps.create_release.outputs.id }}" >> $GITHUB_ENV
      #     echo "Release URL: https://github.com/${{ github.repository }}/releases/tag/${{ steps.create_release.outputs.tag_name }}"
      
  generate-and-release-root:
    runs-on: ubuntu-latest
    permissions:
      contents: 'write'
      packages: 'write'

    if: ${{ inputs.publish_root == true }}
    steps:
      # 1.2 Checkout репозиторий
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Убедитесь, что весь репозиторий загружен, включая историю коммитов

      # 2.2 Установить зависимости
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # 3.2 Установить зависимости для работы с git
      - name: Install dependencies
        run: |
          npm install -g conventional-changelog-cli

      # 4.2 Проверить изменения в root
      - name: Check changes in root
        id: changes-root
        run: |
          # Обновляем локальные данные о ветке master
          git fetch origin master

          # Проверяем, существует ли ветка master на удалённом репозитории
          BASE_BRANCH="origin/master"
          if git rev-parse --verify $BASE_BRANCH >/dev/null 2>&1; then
            # Находим общий предок между текущей веткой и master
            BASE_COMMIT=$(git merge-base HEAD $BASE_BRANCH)
          else
            echo "No common ancestor found. Using initial commit as base."
            BASE_COMMIT=$(git rev-list --max-parents=0 HEAD)
          fi

          # Сравниваем изменения в root относительно базового коммита
          git diff --quiet $BASE_COMMIT HEAD -- . ':!packages/' || echo "Changes detected" >> $GITHUB_ENV

          # Если изменения есть, сохраняем флаг
          if [ $? -eq 0 ]; then
            echo "changes=true" >> $GITHUB_ENV
          else
            echo "changes=false" >> $GITHUB_ENV
          fi
          
      # 5.2 Сбор данных коммитов
      - name: Generate changelog for root
        if: env.changes == 'true'
        run: |
          # Генерация CHANGELOG.md для root
          npm run changelog:root

      # 6. Закоммитить изменения в changelog
      - name: Commit changelog updates
        if: env.changes == 'true'
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add packages/front-end/CHANGELOG.md
          git commit -m "chore(root): update changelog [skip ci]" || echo "No changes to commit"
      
      # 7. Запушить изменения
      - name: Push changelog to repository
        if: env.changes == 'true'
        run: |
          git push origin HEAD

      # 6.2 Создать релиз для root, если есть изменения
      - name: Create GitHub Release for root
        if: env.changes == 'true'
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: root-v${{ github.run_id }}
          release_name: Root Release v${{ github.run_id }}
          draft: true
          prerelease: false
          body: |
            See the latest changes for root in [CHANGELOG.md](CHANGELOG.md).

      - name: Save Release ID
        run: |
          echo "RELEASE_ID=${{ steps.create_release.outputs.id }}" >> $GITHUB_ENV
          echo "Release URL: https://github.com/${{ github.repository }}/releases/tag/${{ steps.create_release.outputs.tag_name }}"

  # create-release:
    # needs: generate-changelog
    # runs-on: ubuntu-latest

    # steps:
    #   # 1. Checkout репозиторий
    #   - name: Checkout repository
    #     uses: actions/checkout@v3

    #   # 2. Создать релиз
    #   - name: Create GitHub Release
    #     uses: actions/create-release@v1
    #     with:
    #       tag_name: ${{ github.ref }}
    #       release_name: Release ${{ github.ref }}
    #       draft: false
    #       prerelease: false
    #       body: |
    #         Changelog updates for:
    #         - [root](CHANGELOG.md)
    #         - [front-end](packages/front-end/CHANGELOG.md)
    #         - [plugin-1](packages/plugin-1/CHANGELOG.md)