name: Create Issue Reference in PR Template

on:
  pull_request:
    types: [opened, synchronize] # edited,

jobs:
  update-template:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
    - name: Extract issue number from branch name
      env:
        GITHUB_HEAD_REF: ${{ github.head_ref }}
      run: |
        BRANCH_NAME="${GITHUB_HEAD_REF}"
        # accept 
        # `issue-123/*`, 
        # `issue_123/*`, 
        # `*/issue-123/*`, 
        # `*/issue_123/*`
        if [[ "$BRANCH_NAME" =~ (issue[-_])([0-9]+) ]]; then
          ISSUE_NUMBER="${BASH_REMATCH[2]}"
        else
          ISSUE_NUMBER=""
        fi
        echo "ISSUE_NUMBER=$ISSUE_NUMBER" >> $GITHUB_ENV
        echo "ISSUE_NUMBER: $ISSUE_NUMBER"

    - name: Update pull request template
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PR_NUMBER: ${{ github.event.pull_request.number }}
      run: |
        ISSUE_NUMBER="${ISSUE_NUMBER}"
        PR_NUMBER="${PR_NUMBER}"
        REPO_OWNER="${GITHUB_REPOSITORY_OWNER}"
        REPO_NAME="${GITHUB_REPOSITORY#*/}"
        GITHUB_TOKEN="${GITHUB_TOKEN}"
        ISSUE_LINK="https://github.com/${REPO_OWNER}/${REPO_NAME}/issues/${ISSUE_NUMBER}"
        PR_URL="https://api.github.com/repos/${REPO_OWNER}/${REPO_NAME}/pulls/${PR_NUMBER}"

        echo "Fetching PR #${PR_NUMBER} from ${REPO_OWNER}/${REPO_NAME}"

        # Get the current PR body (remove any possible \r in the output)
        PR_BODY=$(curl -s -H "Authorization: Bearer ${GITHUB_TOKEN}" \
                        -H "Accept: application/vnd.github.v3+json" \
                        "${PR_URL}" | jq -r '.body' | sed 's/\r$//')

        if [ -z "$PR_BODY" ] || [ "$PR_BODY" == "null" ]; then
          echo "Error: Unable to fetch PR body or PR not found."
          exit 1
        fi

        # Update PR body, inserting issue number instead of comment <!-- ISSUE_LINK -->
        UPDATED_BODY=$(echo "$PR_BODY" | sed "s|<!-- ISSUE_LINK -->|${ISSUE_NUMBER:+[#${ISSUE_NUMBER}](${ISSUE_LINK})}|")

        # Update PR body with GH API
        RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" -X PATCH "${PR_URL}" \
            -H "Authorization: Bearer ${GITHUB_TOKEN}" \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Content-Type: application/json" \
            --data "$(jq -n --arg body "$UPDATED_BODY" '$body | gsub("\r"; "") | {body: .}')" )

        if [ "$RESPONSE" -ne 200 ]; then
          echo "Error: Failed to update PR. HTTP Status: $RESPONSE"
          exit 1
        fi

        echo "PR #${PR_NUMBER} updated successfully with issue link: ${ISSUE_LINK}"
